server:
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: ${LEGEND_OMNIBUS_SDLC_PORT}
      maxRequestHeaderSize: 128KiB
  adminConnectors:
    - type: http
      port: ${LEGEND_OMNIBUS_SDLC_ADMIN_PORT}
  gzip:
    includedMethods:
      - GET
      - POST
  requestLog:
    type: classic
    level: "OFF"
    appenders:
      - type: console
        logFormat: "OFF"
  rootPath: /api
sessionCookie: LEGEND_SDLC_JSESSIONID
logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%thread] %c - %m%n"
swagger:
  resourcePackage: org.finos.legend.sdlc.server.resources
  title: Legend SDLC
  version: local-snapshot
  schemes: []

pac4j:
  callbackPrefix: /api/pac4j
  clients:
    - org.finos.legend.server.pac4j.gitlab.GitlabClient:
        name: gitlab
        clientId: ${LEGEND_OMNIBUS_CONFIG_GITLAB_OAUTH_APPLICATION_ID}
        secret: ${LEGEND_OMNIBUS_CONFIG_GITLAB_OAUTH_APPLICATION_SECRET}
        discoveryUri: https://gitlab.com/.well-known/openid-configuration
        scope: openid profile api
  bypassPaths:
    - /api/info
    - /api/server/info
    - /api/server/platforms
    - /api/auth/authorized

applicationName: Legend SDLC
filterPriorities:
  GitLab: 1
  org.pac4j.j2e.filter.CallbackFilter: 2
  org.pac4j.j2e.filter.SecurityFilter: 3
  CORS: 4
features:
  canCreateProject: true
  canCreateVersion: true
projectStructure:
  projectCreation: {}
  extensionProvider:
    org.finos.legend.sdlc.server.gitlab.finos.FinosGitlabProjectStructureExtensionProvider:
      {}
  platforms:
    legend-engine:
      groupId: org.finos.legend.engine
      platformVersion:
        version: ${LEGEND_OMNIBUS_ENGINE_VERSION}
    legend-sdlc:
      groupId: org.finos.legend.sdlc
      platformVersion:
        version: ${LEGEND_OMNIBUS_SDLC_VERSION}
gitLab:
  newProjectVisibility: public
  projectTag: legend
  projectIdPrefix: OMNIBUS
  server:
    scheme: https
    host: gitlab.com
    port: 443
  app:
    id: ${LEGEND_OMNIBUS_CONFIG_GITLAB_OAUTH_APPLICATION_ID}
    secret: ${LEGEND_OMNIBUS_CONFIG_GITLAB_OAUTH_APPLICATION_SECRET}
    redirectURI: ${LEGEND_OMNIBUS_CONFIG_GITLAB_OAUTH_REDIRECT_BASE_URL}/sdlc/api/auth/callback
