#!/bin/bash

source .env

# Build the image
docker build \
  --platform=linux/amd64 \
  --build-arg LEGEND_OMNIBUS_SDLC_VERSION=$LEGEND_OMNIBUS_SDLC_VERSION \
  --build-arg LEGEND_OMNIBUS_ENGINE_VERSION=$LEGEND_OMNIBUS_ENGINE_VERSION \
  --build-arg LEGEND_OMNIBUS_STUDIO_VERSION=$LEGEND_OMNIBUS_STUDIO_VERSION \
  \
  --build-arg LEGEND_OMNIBUS_GITLAB_PORT=$LEGEND_OMNIBUS_GITLAB_PORT \
  --build-arg LEGEND_OMNIBUS_GITLAB_ROOT_USER=$LEGEND_OMNIBUS_GITLAB_ROOT_USER \
  --build-arg LEGEND_OMNIBUS_GITLAB_PRIVATE_ACCESS_TOKEN=$LEGEND_OMNIBUS_GITLAB_PRIVATE_ACCESS_TOKEN \
  --build-arg LEGEND_OMNIBUS_GITLAB_ROOT_PASSWORD=$LEGEND_OMNIBUS_GITLAB_ROOT_PASSWORD \
  \
  --build-arg LEGEND_OMNIBUS_ENGINE_PORT=$LEGEND_OMNIBUS_ENGINE_PORT \
  --build-arg LEGEND_OMNIBUS_ENGINE_METADATA_PURE_HOST=$LEGEND_OMNIBUS_ENGINE_METADATA_PURE_HOST \
  --build-arg LEGEND_OMNIBUS_ENGINE_METADATA_PURE_PORT=$LEGEND_OMNIBUS_ENGINE_METADATA_PURE_PORT \
  --build-arg LEGEND_OMNIBUS_ENGINE_METADATA_ALLOY_HOST=$LEGEND_OMNIBUS_ENGINE_METADATA_ALLOY_HOST \
  --build-arg LEGEND_OMNIBUS_ENGINE_METADATA_ALLOY_PORT=$LEGEND_OMNIBUS_ENGINE_METADATA_ALLOY_PORT \
  --build-arg LEGEND_OMNIBUS_ENGINE_TEMP_DB_PORT=$LEGEND_OMNIBUS_ENGINE_TEMP_DB_PORT \
  \
  --build-arg LEGEND_OMNIBUS_SDLC_PORT=$LEGEND_OMNIBUS_SDLC_PORT \
  --build-arg LEGEND_OMNIBUS_SDLC_ADMIN_PORT=$LEGEND_OMNIBUS_SDLC_ADMIN_PORT \
  --build-arg LEGEND_OMNIBUS_SDLC_PROJECT_TAG=$LEGEND_OMNIBUS_SDLC_PROJECT_TAG \
  --build-arg LEGEND_OMNIBUS_SDLC_PROJECT_ID_PREFIX=$LEGEND_OMNIBUS_SDLC_PROJECT_ID_PREFIX \
  --build-arg LEGEND_OMNIBUS_SDLC_GITLAB_APP_ID=$LEGEND_OMNIBUS_SDLC_GITLAB_APP_ID \
  --build-arg LEGEND_OMNIBUS_SDLC_GITLAB_APP_SECRET=$LEGEND_OMNIBUS_SDLC_GITLAB_APP_SECRET \
  --build-arg LEGEND_OMNIBUS_SDLC_REDIRECT_URI=$LEGEND_OMNIBUS_SDLC_REDIRECT_URI \
  \
  --build-arg LEGEND_OMNIBUS_STUDIO_PORT=$LEGEND_OMNIBUS_STUDIO_PORT \
  \
  --build-arg LEGEND_OMNIBUS_NGINX_PORT=$LEGEND_OMNIBUS_NGINX_PORT \
  \
  --build-arg LEGEND_OMNIBUS_SUPERVISOR_PORT=$LEGEND_OMNIBUS_SUPERVISOR_PORT \
  --build-arg LEGEND_OMNIBUS_SUPERVISOR_USERNAME=$LEGEND_OMNIBUS_SUPERVISOR_USERNAME \
  --build-arg LEGEND_OMNIBUS_SUPERVISOR_PASSWORD=$LEGEND_OMNIBUS_SUPERVISOR_PASSWORD \
  \
  . -t legend-omnibus
