apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legend.fullname" . }}-mongo
  labels:
    app: mongo
    {{- include "legend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: mongo
      {{- include "legend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: mongo
        {{- include "legend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "legend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mongo
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mongo.repository }}:{{ .Values.mongo.tag }}"
          imagePullPolicy: {{ .Values.mongo.pullPolicy }}
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.mongo.env.MONGO_USER }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.mongo.env.MONGO_PASSWORD }}
          args: ["--auth"]
          ports:
            - name: mongo
              containerPort: {{ .Values.mongo.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mongo.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mongo.port }}
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
