apiVersion: v1
kind: Service
metadata:
  name: {{ include "legend.fullname" . }}-studio
  labels:
    
    {{- include "legend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studio.type }}
  ports:
    - port: {{ .Values.studio.port }}
      targetPort: {{ .Values.studio.port }}
      protocol: TCP
      name: studio
  selector:
    app: studio
