apiVersion: v1
kind: Service
metadata:
  name: {{ include "legend.fullname" . }}-engine
  labels:
    app: engine
    {{- include "legend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.engine.type }}
  ports:
    - port: {{ .Values.engine.port }}
      targetPort: {{ .Values.engine.port }}
      protocol: TCP
      name: engine
  selector:
    app: engine
