server:
  type: simple
  applicationContextPath: "/"
  adminContextPath: "/admin"
  connector:
    maxRequestHeaderSize: 32KiB
    type: http
    port: ${LEGEND_OMNIBUS_PURE_IDE_PORT}
  requestLog:
    appenders: []
sessionCookie: LEGEND_PURE_IDE_JSESSIONID
logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%thread] %c - %m%n"
swagger:
  resourcePackage: org.finos.legend
  title: Legend Pure IDE
  uriPrefix: "/"

sourceLocationConfiguration:
  welcomeFileDirectory: "./"
