apiVersion: v1
data:
  uiConfig.json: |
    {
      "appName": "studio",
      "env": "test",
      "sdlc": {
        "url": "__LEGEND_SDLC_URL__/api"
      },
      "metadata": {
        "url": "__LEGEND_DEPOT_URL__/api"
      },
      "engine": {
        "url": "__LEGEND_ENGINE_URL__/api"
      },
      "documentation": {
        "url": "https://legend.finos.org"
      },
      "options": {
        "core": {
          "TEMPORARY__disableServiceRegistration": true
        }
      }
    }
  httpConfig.json: |
    {
      "pac4j": {
        "callbackPrefix": "/studio/log.in",
        "bypassPaths": ["/studio/admin/healthcheck"],
        "mongoUri": "mongodb://__MONGO_USER__:__MONGO_PASSWORD__@__MONGO_HOST__:__MONGO_PORT__",
        "mongoDb": "legend",
        "clients": [
          {
            "org.finos.legend.server.pac4j.gitlab.GitlabClient": {
              "name" : "gitlab",
              "clientId" : "__GITLAB_OAUTH_CLIENT_ID__",
              "secret": "__GITLAB_OAUTH_SECRET__",
              "discoveryUri": "https://__GITLAB_URL__/.well-known/openid-configuration",
              "scope": "openid profile api"
            }
          }
        ],
        "mongoSession": {
          "enabled": true,
          "collection": "userSessions"
        }
      },
      "html5Router": true,
      "routerExemptPaths": [
          "/editor.worker.js",
          "/json.worker.js",
          "/editor.worker.js.map",
          "/json.worker.js.map",
          "/version.json",
          "/config.json",
          "/favicon.ico",
          "/static"
      ],
      "localAssetPaths": {
          "/studio/config.json" : "/config/uiConfig.json"
      },
      "uiPath": "/studio",
      "server": {
        "type": "simple",
        "applicationContextPath": "/",
        "adminContextPath": "/studio/admin",
        "connector": {
          "type": "http",
          "port": __LEGEND_STUDIO_PORT__
        }
      },
      "logging": {
        "level": "INFO",
        "loggers" : {
          "root": { "level": "info"},
          "org.pac4j": { "level": "debug"}
        },
        "appenders": [
          {
            "type": "console"
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  labels:
    app: studio
    {{- include "legend.labels" . | nindent 4 }}
  name: {{ include "legend.fullname" . }}-studio-template