name: Build Showcases Index

on:
  push:
    branches:
      - master
    paths:
      - "showcases/**"
  workflow_dispatch: {}
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-index:
    name: Build Showcase Index
    # There is currently no way to limit workflow dispatch to only allow default branch
    # so we need to restrict it here
    # See https://github.community/t/limit-branch-for-workflow-dispatch/122099
    if: github.ref == 'refs/heads/master' && github.repository == 'finos/legend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.FINOS_GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.email "37706051+finos-admin@users.noreply.github.com"
          git config --global user.name "FINOS Administrator"
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - name: Update Showcases Index
        run: |
          npm install
          npm run update:showcases-index
