name: (Manual) Create Docker Release

on:
  workflow_dispatch:
    inputs:
      legend-engine-version:
        description: "New release version for Legend Engine"
        required: false
      legend-sdlc-version:
        description: "New release version for Legend SDLC"
        required: false
      legend-studio-version:
        description: "New release version for Legend Studio"
        required: false

permissions:
  contents: write

jobs:
  create-docker-release:
    # There is currently no way to limit workflow dispatch to only allow default branch
    # so we need to restrict it here
    # See https://github.community/t/limit-branch-for-workflow-dispatch/122099
    if: github.ref == 'refs/heads/master' && github.repository == 'finos/legend'
    name: Create Docker Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - name: Create New Release
        run: |
          date > generated.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: finos
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Omnibus to Docker
        working-directory: ./installers/omnibus
        run: ./scripts/publish-to-docker.sh
